/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type BankCard = {
  /**
   * @description ID of the bank card
   * @type string | undefined
   */
  cardId?: string
  /**
   * @description Card number
   * @type string
   */
  cardNumber: string
  /**
   * @description Expiration date of the card (MM/YY format)
   * @type string
   */
  expirationDate: string
  /**
   * @description CVV of the card
   * @type string
   */
  cvv: string
  /**
   * @description ID of the customer associated with the bank card
   * @type string
   */
  customerId: string
}