/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type Customer = {
  /**
   * @description ID of the customer
   * @type string
   */
  customerId: string
  /**
   * @description Name of the customer
   * @type string
   */
  name: string
  /**
   * @description Email of the customer
   * @type string
   */
  email: string
  /**
   * @description Contact information of the customer (E.164 format)
   * @type string | undefined
   */
  contact?: string
  /**
   * @description Photo URL of the customer
   * @type string | undefined
   */
  photo?: string
}
