/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteWebsitesCustomersBankcardsCardidPathParams = {
  /**
   * @description ID of the bank card
   * @type string
   */
  cardId: string
}

/**
 * @description Bank card deleted successfully
 */
export type DeleteWebsitesCustomersBankcardsCardid204 = any

/**
 * @description Bank card not found
 */
export type DeleteWebsitesCustomersBankcardsCardid404 = any

/**
 * @description Error deleting bank card
 */
export type DeleteWebsitesCustomersBankcardsCardid500 = any

export type DeleteWebsitesCustomersBankcardsCardidMutationResponse = DeleteWebsitesCustomersBankcardsCardid204

export type DeleteWebsitesCustomersBankcardsCardidMutation = {
  Response: DeleteWebsitesCustomersBankcardsCardid204
  PathParams: DeleteWebsitesCustomersBankcardsCardidPathParams
  Errors: DeleteWebsitesCustomersBankcardsCardid404 | DeleteWebsitesCustomersBankcardsCardid500
}