/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DeleteWebsitesCustomersAddressesAddressidPathParams = {
  /**
   * @description The ID of the address to delete
   * @type string, uuid
   */
  addressId: string
}

/**
 * @description Address deleted successfully
 */
export type DeleteWebsitesCustomersAddressesAddressid204 = any

/**
 * @description Address not found
 */
export type DeleteWebsitesCustomersAddressesAddressid404 = {
  /**
   * @type string | undefined
   */
  error?: string
}

/**
 * @description Error deleting address
 */
export type DeleteWebsitesCustomersAddressesAddressid500 = {
  /**
   * @type string | undefined
   */
  error?: string
}

export type DeleteWebsitesCustomersAddressesAddressidMutationResponse =
  DeleteWebsitesCustomersAddressesAddressid204

export type DeleteWebsitesCustomersAddressesAddressidMutation = {
  Response: DeleteWebsitesCustomersAddressesAddressid204
  PathParams: DeleteWebsitesCustomersAddressesAddressidPathParams
  Errors:
    | DeleteWebsitesCustomersAddressesAddressid404
    | DeleteWebsitesCustomersAddressesAddressid500
}
