/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Address } from './Address.ts'

/**
 * @description List of addresses
 */
export type GetWebsitesCustomersAddresses200 = Address[]

/**
 * @description Error fetching addresses
 */
export type GetWebsitesCustomersAddresses500 = {
  /**
   * @type string | undefined
   */
  error?: string
}

export type GetWebsitesCustomersAddressesQueryResponse = GetWebsitesCustomersAddresses200

export type GetWebsitesCustomersAddressesQuery = {
  Response: GetWebsitesCustomersAddresses200
  Errors: GetWebsitesCustomersAddresses500
}