/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type GetWebsitesCustomersBankcardsCustomerCustomeridPathParams = {
  /**
   * @description ID of the customer
   * @type string
   */
  customerId: string
}

/**
 * @description List of bank cards
 */
export type GetWebsitesCustomersBankcardsCustomerCustomerid200 = any

/**
 * @description Error fetching bank cards
 */
export type GetWebsitesCustomersBankcardsCustomerCustomerid500 = any

export type GetWebsitesCustomersBankcardsCustomerCustomeridQueryResponse = GetWebsitesCustomersBankcardsCustomerCustomerid200

export type GetWebsitesCustomersBankcardsCustomerCustomeridQuery = {
  Response: GetWebsitesCustomersBankcardsCustomerCustomerid200
  PathParams: GetWebsitesCustomersBankcardsCustomerCustomeridPathParams
  Errors: GetWebsitesCustomersBankcardsCustomerCustomerid500
}