/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Bank card created successfully
 */
export type PostWebsitesCustomersBankcards201 = any

/**
 * @description Error creating bank card
 */
export type PostWebsitesCustomersBankcards400 = any

export type PostWebsitesCustomersBankcardsMutationRequest = {
  /**
   * @description Card number
   * @type string | undefined
   */
  cardNumber?: string
  /**
   * @description Expiration date of the card
   * @type string | undefined
   */
  expirationDate?: string
  /**
   * @description CVV of the card
   * @type string | undefined
   */
  cvv?: string
  /**
   * @description ID of the customer
   * @type string | undefined
   */
  customerId?: string
}

export type PostWebsitesCustomersBankcardsMutationResponse =
  PostWebsitesCustomersBankcards201

export type PostWebsitesCustomersBankcardsMutation = {
  Response: PostWebsitesCustomersBankcards201
  Request: PostWebsitesCustomersBankcardsMutationRequest
  Errors: PostWebsitesCustomersBankcards400
}
