/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Address } from './Address.ts'

/**
 * @description Address created successfully
 */
export type PostWebsitesCustomersAddresses201 = Address

/**
 * @description Validation error or maximum address limit reached
 */
export type PostWebsitesCustomersAddresses400 = {
  /**
   * @type string | undefined
   */
  error?: string
}

/**
 * @description Address already exists for this customer
 */
export type PostWebsitesCustomersAddresses409 = any

export type PostWebsitesCustomersAddressesMutationRequest = Address

export type PostWebsitesCustomersAddressesMutationResponse = PostWebsitesCustomersAddresses201

export type PostWebsitesCustomersAddressesMutation = {
  Response: PostWebsitesCustomersAddresses201
  Request: PostWebsitesCustomersAddressesMutationRequest
  Errors: PostWebsitesCustomersAddresses400 | PostWebsitesCustomersAddresses409
}