/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type PutWebsitesCustomersBankcardsCardidPathParams = {
  /**
   * @description ID of the bank card
   * @type string
   */
  cardId: string
}

/**
 * @description Bank card updated successfully
 */
export type PutWebsitesCustomersBankcardsCardid200 = any

/**
 * @description Error updating bank card
 */
export type PutWebsitesCustomersBankcardsCardid400 = any

/**
 * @description Bank card not found
 */
export type PutWebsitesCustomersBankcardsCardid404 = any

export type PutWebsitesCustomersBankcardsCardidMutationRequest = {
  /**
   * @type string | undefined
   */
  cardNumber?: string
  /**
   * @type string | undefined
   */
  expirationDate?: string
  /**
   * @type string | undefined
   */
  cvv?: string
}

export type PutWebsitesCustomersBankcardsCardidMutationResponse =
  PutWebsitesCustomersBankcardsCardid200

export type PutWebsitesCustomersBankcardsCardidMutation = {
  Response: PutWebsitesCustomersBankcardsCardid200
  Request: PutWebsitesCustomersBankcardsCardidMutationRequest
  PathParams: PutWebsitesCustomersBankcardsCardidPathParams
  Errors:
    | PutWebsitesCustomersBankcardsCardid400
    | PutWebsitesCustomersBankcardsCardid404
}
