/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Address } from './Address.ts'

export type PutWebsitesCustomersAddressesAddressidPathParams = {
  /**
   * @description The ID of the address to update
   * @type string, uuid
   */
  addressId: string
}

/**
 * @description Address updated successfully
 */
export type PutWebsitesCustomersAddressesAddressid200 = Address

/**
 * @description Validation error
 */
export type PutWebsitesCustomersAddressesAddressid400 = {
  /**
   * @type string | undefined
   */
  error?: string
}

/**
 * @description Address not found
 */
export type PutWebsitesCustomersAddressesAddressid404 = {
  /**
   * @type string | undefined
   */
  error?: string
}

export type PutWebsitesCustomersAddressesAddressidMutationRequest = Address

export type PutWebsitesCustomersAddressesAddressidMutationResponse = PutWebsitesCustomersAddressesAddressid200

export type PutWebsitesCustomersAddressesAddressidMutation = {
  Response: PutWebsitesCustomersAddressesAddressid200
  Request: PutWebsitesCustomersAddressesAddressidMutationRequest
  PathParams: PutWebsitesCustomersAddressesAddressidPathParams
  Errors: PutWebsitesCustomersAddressesAddressid400 | PutWebsitesCustomersAddressesAddressid404
}