/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, UseSuspenseQueryOptions, UseSuspenseQueryResult } from '@tanstack/react-query'
import type {
  GetWebsitesCustomersBankcardsCustomerCustomeridQueryResponse,
  GetWebsitesCustomersBankcardsCustomerCustomeridPathParams,
  GetWebsitesCustomersBankcardsCustomerCustomerid500,
} from '../types/GetWebsitesCustomersBankcardsCustomerCustomerid.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getWebsitesCustomersBankcardsCustomerCustomeridSuspenseQueryKey = (
  customerId: GetWebsitesCustomersBankcardsCustomerCustomeridPathParams['customerId'],
) => [{ url: '/websites/customers/bankcards/customer/:customerId', params: { customerId: customerId } }] as const

export type GetWebsitesCustomersBankcardsCustomerCustomeridSuspenseQueryKey = ReturnType<typeof getWebsitesCustomersBankcardsCustomerCustomeridSuspenseQueryKey>

/**
 * @summary Get all bank cards for a customer
 * {@link /websites/customers/bankcards/customer/:customerId}
 */
export async function getWebsitesCustomersBankcardsCustomerCustomeridSuspense(
  customerId: GetWebsitesCustomersBankcardsCustomerCustomeridPathParams['customerId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    GetWebsitesCustomersBankcardsCustomerCustomeridQueryResponse,
    ResponseErrorConfig<GetWebsitesCustomersBankcardsCustomerCustomerid500>,
    unknown
  >({ method: 'GET', url: `/websites/customers/bankcards/customer/${customerId}`, baseURL: 'http://localhost:2001/api', ...requestConfig })
  return res.data
}

export function getWebsitesCustomersBankcardsCustomerCustomeridSuspenseQueryOptions(
  customerId: GetWebsitesCustomersBankcardsCustomerCustomeridPathParams['customerId'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getWebsitesCustomersBankcardsCustomerCustomeridSuspenseQueryKey(customerId)
  return queryOptions<
    GetWebsitesCustomersBankcardsCustomerCustomeridQueryResponse,
    ResponseErrorConfig<GetWebsitesCustomersBankcardsCustomerCustomerid500>,
    GetWebsitesCustomersBankcardsCustomerCustomeridQueryResponse,
    typeof queryKey
  >({
    enabled: !!customerId,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getWebsitesCustomersBankcardsCustomerCustomeridSuspense(customerId, config)
    },
  })
}

/**
 * @summary Get all bank cards for a customer
 * {@link /websites/customers/bankcards/customer/:customerId}
 */
export function useGetWebsitesCustomersBankcardsCustomerCustomeridSuspense<
  TData = GetWebsitesCustomersBankcardsCustomerCustomeridQueryResponse,
  TQueryKey extends QueryKey = GetWebsitesCustomersBankcardsCustomerCustomeridSuspenseQueryKey,
>(
  customerId: GetWebsitesCustomersBankcardsCustomerCustomeridPathParams['customerId'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetWebsitesCustomersBankcardsCustomerCustomeridQueryResponse,
        ResponseErrorConfig<GetWebsitesCustomersBankcardsCustomerCustomerid500>,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getWebsitesCustomersBankcardsCustomerCustomeridSuspenseQueryKey(customerId)

  const query = useSuspenseQuery(
    {
      ...(getWebsitesCustomersBankcardsCustomerCustomeridSuspenseQueryOptions(customerId, config) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<TData, ResponseErrorConfig<GetWebsitesCustomersBankcardsCustomerCustomerid500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}