/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type { RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { GetWebsitesCustomersAddressesQueryResponse, GetWebsitesCustomersAddresses500 } from '../types/GetWebsitesCustomersAddresses.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getWebsitesCustomersAddressesQueryKey = () => [{ url: '/websites/customers/addresses' }] as const

export type GetWebsitesCustomersAddressesQueryKey = ReturnType<typeof getWebsitesCustomersAddressesQueryKey>

/**
 * @summary Get all addresses for the authenticated customer
 * {@link /websites/customers/addresses}
 */
export async function getWebsitesCustomersAddresses(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetWebsitesCustomersAddressesQueryResponse, ResponseErrorConfig<GetWebsitesCustomersAddresses500>, unknown>({
    method: 'GET',
    url: `/websites/customers/addresses`,
    baseURL: 'http://localhost:2001/api',
    ...requestConfig,
  })
  return res.data
}

export function getWebsitesCustomersAddressesQueryOptions(config: Partial<RequestConfig> & { client?: typeof client } = {}) {
  const queryKey = getWebsitesCustomersAddressesQueryKey()
  return queryOptions<
    GetWebsitesCustomersAddressesQueryResponse,
    ResponseErrorConfig<GetWebsitesCustomersAddresses500>,
    GetWebsitesCustomersAddressesQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getWebsitesCustomersAddresses(config)
    },
  })
}

/**
 * @summary Get all addresses for the authenticated customer
 * {@link /websites/customers/addresses}
 */
export function useGetWebsitesCustomersAddresses<
  TData = GetWebsitesCustomersAddressesQueryResponse,
  TQueryData = GetWebsitesCustomersAddressesQueryResponse,
  TQueryKey extends QueryKey = GetWebsitesCustomersAddressesQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<GetWebsitesCustomersAddressesQueryResponse, ResponseErrorConfig<GetWebsitesCustomersAddresses500>, TData, TQueryData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const { query: { client: queryClient, ...queryOptions } = {}, client: config = {} } = options ?? {}
  const queryKey = queryOptions?.queryKey ?? getWebsitesCustomersAddressesQueryKey()

  const query = useQuery(
    {
      ...(getWebsitesCustomersAddressesQueryOptions(config) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<GetWebsitesCustomersAddresses500>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}