/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type { UseMutationOptions, QueryClient } from '@tanstack/react-query'
import type {
  PostWebsitesCustomersAddressesMutationRequest,
  PostWebsitesCustomersAddressesMutationResponse,
  PostWebsitesCustomersAddresses400,
  PostWebsitesCustomersAddresses409,
} from '../types/PostWebsitesCustomersAddresses.ts'
import { useMutation } from '@tanstack/react-query'

export const postWebsitesCustomersAddressesMutationKey = () =>
  [{ url: '/websites/customers/addresses' }] as const

export type PostWebsitesCustomersAddressesMutationKey = ReturnType<
  typeof postWebsitesCustomersAddressesMutationKey
>

/**
 * @summary Create a new address
 * {@link /websites/customers/addresses}
 */
export async function postWebsitesCustomersAddresses(
  data: PostWebsitesCustomersAddressesMutationRequest,
  config: Partial<
    RequestConfig<PostWebsitesCustomersAddressesMutationRequest>
  > & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    PostWebsitesCustomersAddressesMutationResponse,
    ResponseErrorConfig<
      PostWebsitesCustomersAddresses400 | PostWebsitesCustomersAddresses409
    >,
    PostWebsitesCustomersAddressesMutationRequest
  >({
    method: 'POST',
    url: `/websites/customers/addresses`,
    baseURL: 'http://localhost:2001/api',
    data,
    ...requestConfig,
  })
  return res.data
}

/**
 * @summary Create a new address
 * {@link /websites/customers/addresses}
 */
export function usePostWebsitesCustomersAddresses<TContext>(
  options: {
    mutation?: UseMutationOptions<
      PostWebsitesCustomersAddressesMutationResponse,
      ResponseErrorConfig<
        PostWebsitesCustomersAddresses400 | PostWebsitesCustomersAddresses409
      >,
      { data: PostWebsitesCustomersAddressesMutationRequest },
      TContext
    > & { client?: QueryClient }
    client?: Partial<
      RequestConfig<PostWebsitesCustomersAddressesMutationRequest>
    > & { client?: typeof client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey =
    mutationOptions.mutationKey ?? postWebsitesCustomersAddressesMutationKey()

  return useMutation<
    PostWebsitesCustomersAddressesMutationResponse,
    ResponseErrorConfig<
      PostWebsitesCustomersAddresses400 | PostWebsitesCustomersAddresses409
    >,
    { data: PostWebsitesCustomersAddressesMutationRequest },
    TContext
  >(
    {
      mutationFn: async ({ data }) => {
        return postWebsitesCustomersAddresses(data, config)
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}
