/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from '@tanstack/react-query'
import type {
  GetWebsitesEcommerceOrdersQueryResponse,
  GetWebsitesEcommerceOrders500,
} from '../types/GetWebsitesEcommerceOrders.ts'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const getWebsitesEcommerceOrdersQueryKey = () =>
  [{ url: '/websites/ecommerce/orders' }] as const

export type GetWebsitesEcommerceOrdersQueryKey = ReturnType<
  typeof getWebsitesEcommerceOrdersQueryKey
>

/**
 * @summary Lista todas as encomendas do cliente autenticado
 * {@link /websites/ecommerce/orders}
 */
export async function getWebsitesEcommerceOrders(
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    GetWebsitesEcommerceOrdersQueryResponse,
    ResponseErrorConfig<GetWebsitesEcommerceOrders500>,
    unknown
  >({
    method: 'GET',
    url: `/websites/ecommerce/orders`,
    baseURL: 'http://localhost:2001/api',
    ...requestConfig,
  })
  return res.data
}

export function getWebsitesEcommerceOrdersQueryOptions(
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getWebsitesEcommerceOrdersQueryKey()
  return queryOptions<
    GetWebsitesEcommerceOrdersQueryResponse,
    ResponseErrorConfig<GetWebsitesEcommerceOrders500>,
    GetWebsitesEcommerceOrdersQueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getWebsitesEcommerceOrders(config)
    },
  })
}

/**
 * @summary Lista todas as encomendas do cliente autenticado
 * {@link /websites/ecommerce/orders}
 */
export function useGetWebsitesEcommerceOrders<
  TData = GetWebsitesEcommerceOrdersQueryResponse,
  TQueryData = GetWebsitesEcommerceOrdersQueryResponse,
  TQueryKey extends QueryKey = GetWebsitesEcommerceOrdersQueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetWebsitesEcommerceOrdersQueryResponse,
        ResponseErrorConfig<GetWebsitesEcommerceOrders500>,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {}
  const queryKey =
    queryOptions?.queryKey ?? getWebsitesEcommerceOrdersQueryKey()

  const query = useQuery(
    {
      ...(getWebsitesEcommerceOrdersQueryOptions(
        config,
      ) as unknown as QueryObserverOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<QueryObserverOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<GetWebsitesEcommerceOrders500>
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
