/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from '@kubb/plugin-client/clients/axios'
import type {
  RequestConfig,
  ResponseErrorConfig,
} from '@kubb/plugin-client/clients/axios'
import type {
  QueryKey,
  QueryClient,
  UseSuspenseQueryOptions,
  UseSuspenseQueryResult,
} from '@tanstack/react-query'
import type {
  GetWebsitesEcommerceOrdersIdQueryResponse,
  GetWebsitesEcommerceOrdersIdPathParams,
  GetWebsitesEcommerceOrdersId404,
  GetWebsitesEcommerceOrdersId500,
} from '../types/GetWebsitesEcommerceOrdersId.ts'
import { queryOptions, useSuspenseQuery } from '@tanstack/react-query'

export const getWebsitesEcommerceOrdersIdSuspenseQueryKey = (
  id: GetWebsitesEcommerceOrdersIdPathParams['id'],
) => [{ url: '/websites/ecommerce/orders/:id', params: { id: id } }] as const

export type GetWebsitesEcommerceOrdersIdSuspenseQueryKey = ReturnType<
  typeof getWebsitesEcommerceOrdersIdSuspenseQueryKey
>

/**
 * @summary Obtém uma encomenda específica pelo ID para o cliente autenticado
 * {@link /websites/ecommerce/orders/:id}
 */
export async function getWebsitesEcommerceOrdersIdSuspense(
  id: GetWebsitesEcommerceOrdersIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<
    GetWebsitesEcommerceOrdersIdQueryResponse,
    ResponseErrorConfig<
      GetWebsitesEcommerceOrdersId404 | GetWebsitesEcommerceOrdersId500
    >,
    unknown
  >({
    method: 'GET',
    url: `/websites/ecommerce/orders/${id}`,
    baseURL: 'http://localhost:2001/api',
    ...requestConfig,
  })
  return res.data
}

export function getWebsitesEcommerceOrdersIdSuspenseQueryOptions(
  id: GetWebsitesEcommerceOrdersIdPathParams['id'],
  config: Partial<RequestConfig> & { client?: typeof client } = {},
) {
  const queryKey = getWebsitesEcommerceOrdersIdSuspenseQueryKey(id)
  return queryOptions<
    GetWebsitesEcommerceOrdersIdQueryResponse,
    ResponseErrorConfig<
      GetWebsitesEcommerceOrdersId404 | GetWebsitesEcommerceOrdersId500
    >,
    GetWebsitesEcommerceOrdersIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!id,
    queryKey,
    queryFn: async ({ signal }) => {
      config.signal = signal
      return getWebsitesEcommerceOrdersIdSuspense(id, config)
    },
  })
}

/**
 * @summary Obtém uma encomenda específica pelo ID para o cliente autenticado
 * {@link /websites/ecommerce/orders/:id}
 */
export function useGetWebsitesEcommerceOrdersIdSuspense<
  TData = GetWebsitesEcommerceOrdersIdQueryResponse,
  TQueryKey extends QueryKey = GetWebsitesEcommerceOrdersIdSuspenseQueryKey,
>(
  id: GetWebsitesEcommerceOrdersIdPathParams['id'],
  options: {
    query?: Partial<
      UseSuspenseQueryOptions<
        GetWebsitesEcommerceOrdersIdQueryResponse,
        ResponseErrorConfig<
          GetWebsitesEcommerceOrdersId404 | GetWebsitesEcommerceOrdersId500
        >,
        TData,
        TQueryKey
      >
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: typeof client }
  } = {},
) {
  const {
    query: { client: queryClient, ...queryOptions } = {},
    client: config = {},
  } = options ?? {}
  const queryKey =
    queryOptions?.queryKey ?? getWebsitesEcommerceOrdersIdSuspenseQueryKey(id)

  const query = useSuspenseQuery(
    {
      ...(getWebsitesEcommerceOrdersIdSuspenseQueryOptions(
        id,
        config,
      ) as unknown as UseSuspenseQueryOptions),
      queryKey,
      ...(queryOptions as unknown as Omit<UseSuspenseQueryOptions, 'queryKey'>),
    },
    queryClient,
  ) as UseSuspenseQueryResult<
    TData,
    ResponseErrorConfig<
      GetWebsitesEcommerceOrdersId404 | GetWebsitesEcommerceOrdersId500
    >
  > & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
