/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Product } from './Product.ts'

export type GetWebsitesEcommerceCartsHeaderParams = {
  /**
   * @description Secret key for the website
   * @type string
   */
  authorization: string
}

/**
 * @description List of items in the cart
 */
export type GetWebsitesEcommerceCarts200 = {
  /**
   * @description ID of the cart
   * @type string
   */
  cartId: string
  /**
   * @description ID of the customer
   * @type string
   */
  customerId: string
  /**
   * @type array
   */
  products: Product[]
  /**
   * @description Total price of the cart
   * @type number
   */
  shipPrice: number
  /**
   * @description Total price of the cart
   * @type number | undefined
   */
  quantity?: number
}

/**
 * @description Cart not found for the customer
 */
export type GetWebsitesEcommerceCarts404 = any

/**
 * @description Error fetching cart items
 */
export type GetWebsitesEcommerceCarts500 = any

export type GetWebsitesEcommerceCartsQueryResponse = GetWebsitesEcommerceCarts200

export type GetWebsitesEcommerceCartsQuery = {
  Response: GetWebsitesEcommerceCarts200
  HeaderParams: GetWebsitesEcommerceCartsHeaderParams
  Errors: GetWebsitesEcommerceCarts404 | GetWebsitesEcommerceCarts500
}