/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Order } from './Order.ts'

export type GetWebsitesEcommerceOrdersIdPathParams = {
  /**
   * @description ID da encomenda
   * @type string
   */
  id: string
}

/**
 * @description Detalhes da encomenda
 */
export type GetWebsitesEcommerceOrdersId200 = Order

/**
 * @description Encomenda não encontrada
 */
export type GetWebsitesEcommerceOrdersId404 = {
  /**
   * @type string | undefined
   */
  error?: string
}

/**
 * @description Erro ao obter encomenda
 */
export type GetWebsitesEcommerceOrdersId500 = {
  /**
   * @type string | undefined
   */
  error?: string
}

export type GetWebsitesEcommerceOrdersIdQueryResponse =
  GetWebsitesEcommerceOrdersId200

export type GetWebsitesEcommerceOrdersIdQuery = {
  Response: GetWebsitesEcommerceOrdersId200
  PathParams: GetWebsitesEcommerceOrdersIdPathParams
  Errors: GetWebsitesEcommerceOrdersId404 | GetWebsitesEcommerceOrdersId500
}
