/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Order } from './Order.ts'

/**
 * @description Lista de encomendas
 */
export type GetWebsitesEcommerceOrders200 = Order[]

/**
 * @description Erro ao obter encomendas
 */
export type GetWebsitesEcommerceOrders500 = {
  /**
   * @type string | undefined
   */
  error?: string
}

export type GetWebsitesEcommerceOrdersQueryResponse =
  GetWebsitesEcommerceOrders200

export type GetWebsitesEcommerceOrdersQuery = {
  Response: GetWebsitesEcommerceOrders200
  Errors: GetWebsitesEcommerceOrders500
}
