/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Product } from './Product.ts'

export type OrderProduct = {
  /**
   * @description ID of the order-product relation
   * @type string
   */
  orderProductId: string
  /**
   * @description ID of the order
   * @type string
   */
  orderId: string
  /**
   * @description ID of the product
   * @type string
   */
  productId: string
  /**
   * @description Quantity of the product in the order
   * @type integer
   */
  quantity: number
  /**
   * @description Price of the product at the time of purchase
   * @type number
   */
  priceAtPurchase: number
  /**
   * @type object | undefined
   */
  product?: Product
}
