/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OrderProduct } from './OrderProduct.ts'

export type Order = {
  /**
   * @description Unique identifier for the order
   * @type string, uuid
   */
  orderId: string
  /**
   * @description Unique identifier for the customer
   * @type string, uuid
   */
  customerId: string
  /**
   * @description Unique identifier for the user
   * @type string, uuid
   */
  userId: string
  /**
   * @description Total price of the order
   * @type number, float
   */
  price: number
  /**
   * @description Timestamp when the order was created
   * @type string | undefined, date-time
   */
  createdAt?: string
  /**
   * @description Timestamp when the order was last updated
   * @type string | undefined, date-time
   */
  updatedAt?: string
  /**
   * @description List of products in the order
   * @type array | undefined
   */
  orderProducts?: OrderProduct[]
  /**
   * @description Shipping address ID
   * @type string | undefined
   */
  shippingAddress?: string
  /**
   * @description Billing address ID
   * @type string | undefined
   */
  billingAddress?: string
}
