/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Product } from './Product.ts'

/**
 * @description Product added to the cart successfully
 */
export type PostWebsitesEcommerceCarts200 = {
  /**
   * @description ID of the cart
   * @type string | undefined
   */
  cartId?: string
  /**
   * @description ID of the customer
   * @type string | undefined
   */
  customerId?: string
  /**
   * @type array | undefined
   */
  products?: Product[]
  /**
   * @description Total price of the cart
   * @type number | undefined
   */
  shipPrice?: number
}

/**
 * @description Invalid quantity or operation
 */
export type PostWebsitesEcommerceCarts400 = any

/**
 * @description Error adding product to the cart
 */
export type PostWebsitesEcommerceCarts500 = any

export type PostWebsitesEcommerceCartsMutationRequest = {
  /**
   * @description ID of the product to add
   * @type string
   */
  productId: string
  /**
   * @description Quantity of the product to add
   * @type integer
   */
  quantity: number
}

export type PostWebsitesEcommerceCartsMutationResponse = PostWebsitesEcommerceCarts200

export type PostWebsitesEcommerceCartsMutation = {
  Response: PostWebsitesEcommerceCarts200
  Request: PostWebsitesEcommerceCartsMutationRequest
  Errors: PostWebsitesEcommerceCarts400 | PostWebsitesEcommerceCarts500
}