/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description PaymentIntent criado com sucesso
 */
export type PostWebsitesEcommerceOrdersPaymentIntent200 = {
  /**
   * @description Stripe client secret
   * @type string | undefined
   */
  clientSecret?: string
}

/**
 * @description Carrinho vazio
 */
export type PostWebsitesEcommerceOrdersPaymentIntent400 = {
  /**
   * @type string | undefined
   */
  error?: string
}

/**
 * @description Erro ao criar PaymentIntent
 */
export type PostWebsitesEcommerceOrdersPaymentIntent500 = {
  /**
   * @type string | undefined
   */
  error?: string
}

export const postWebsitesEcommerceOrdersPaymentIntentMutationRequestPaymentMethodEnum =
  {
    card: 'card',
    mb_way: 'mb_way',
  } as const

export type PostWebsitesEcommerceOrdersPaymentIntentMutationRequestPaymentMethodEnum =
  (typeof postWebsitesEcommerceOrdersPaymentIntentMutationRequestPaymentMethodEnum)[keyof typeof postWebsitesEcommerceOrdersPaymentIntentMutationRequestPaymentMethodEnum]

export type PostWebsitesEcommerceOrdersPaymentIntentMutationRequest = {
  /**
   * @description ID do cliente
   * @type string
   */
  customerId: string
  /**
   * @description Método de pagamento (card ou mb_way)
   * @type string | undefined
   */
  paymentMethod?: PostWebsitesEcommerceOrdersPaymentIntentMutationRequestPaymentMethodEnum
}

export type PostWebsitesEcommerceOrdersPaymentIntentMutationResponse =
  PostWebsitesEcommerceOrdersPaymentIntent200

export type PostWebsitesEcommerceOrdersPaymentIntentMutation = {
  Response: PostWebsitesEcommerceOrdersPaymentIntent200
  Request: PostWebsitesEcommerceOrdersPaymentIntentMutationRequest
  Errors:
    | PostWebsitesEcommerceOrdersPaymentIntent400
    | PostWebsitesEcommerceOrdersPaymentIntent500
}
