/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Order } from './Order.ts'

/**
 * @description Encomenda criada com sucesso
 */
export type PostWebsitesEcommerceOrders201 = {
  /**
   * @type string | undefined
   */
  message?: string
  /**
   * @type object | undefined
   */
  order?: Order
}

/**
 * @description Carrinho vazio ou morada inválida
 */
export type PostWebsitesEcommerceOrders400 = {
  /**
   * @type string | undefined
   */
  error?: string
}

/**
 * @description Cliente não encontrado
 */
export type PostWebsitesEcommerceOrders404 = {
  /**
   * @type string | undefined
   */
  error?: string
}

/**
 * @description Erro ao criar encomenda
 */
export type PostWebsitesEcommerceOrders500 = {
  /**
   * @type string | undefined
   */
  error?: string
}

export type PostWebsitesEcommerceOrdersMutationRequest = {
  /**
   * @description ID do cliente
   * @type string | undefined
   */
  customerId?: string
  /**
   * @description ID da morada de envio
   * @type string | undefined
   */
  shippingAddress?: string
  /**
   * @description ID da morada de faturação
   * @type string | undefined
   */
  billingAddress?: string
}

export type PostWebsitesEcommerceOrdersMutationResponse =
  PostWebsitesEcommerceOrders201

export type PostWebsitesEcommerceOrdersMutation = {
  Response: PostWebsitesEcommerceOrders201
  Request: PostWebsitesEcommerceOrdersMutationRequest
  Errors:
    | PostWebsitesEcommerceOrders400
    | PostWebsitesEcommerceOrders404
    | PostWebsitesEcommerceOrders500
}
